services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=todo;Username=todo;Password=11111111"
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=11111111
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}